parameters:
  path: ''
  version: 'v1'
steps:
  - bash: |
      if [ -z "$PATH_PARAMETER" ]; then
        echo '##vso[task.logissue type=error;]Missing template parameter "path"'
        echo '##vso[task.complete result=Failed;]DONE'
      fi
    env:
      PATH_PARAMETER: ${{ parameters.path }}
    displayName: Check for required parameters
  - bash: |
      [[ -z "$(system.pullRequest.sourceBranch)" ]] && echo "##vso[task.setvariable variable=SOURCE_BRANCH;]$(build.sourceBranchName)" || echo "##vso[task.setvariable variable=SOURCE_BRANCH;]$(system.pullRequest.sourceBranch)"
    displayName: Set source branch
  - task: CacheBeta@0
    inputs:
      key: |
        yarn-packages-${{ parameters.version }}-$(SOURCE_BRANCH)
        $(build.sourcesDirectory)/yarn.lock
      path: ${{ parameters.path }}
    displayName: Cache Yarn packages
