parameters:
  path: ''
  version: 'v1'
steps:
  - task: CacheBeta@0
    inputs:
      key: |
        yarn-packages-${{ parameters.version }}-$(System.PullRequest.SourceBranch)
        $(Build.SourcesDirectory)/yarn.lock
      path: ${{ parameters.path }}
    displayName: Cache Yarn packages
