parameters:
  path: ''
  version: 'v1'
steps:
  - task: CacheBeta@0
    inputs:
      key: |
        yarn-packages-${{ parameters.version }}-${{ coalesce(variables['System.PullRequest.SourceBranch'], variables['Build.SourceBranchName'], 'master') }}
        $(Build.SourcesDirectory)/yarn.lock
      path: ${{ parameters.path }}
    displayName: Cache Yarn packages
