parameters:
  path: ''
  version: 'v1'
steps:
  - bash: |
      echo 1 ${{ parameters.path }}
      echo 2 $(parameters.path)

      if [[ -z "$PATH_PARAMETER" ]]; then
        echo '##vso[task.logissue type=error;]Missing template parameter "path"'
        echo '##vso[task.complete result=Failed;]DONE'
      fi
    env:
      PATH_PARAMETER: ${{ parameters.path }}
    displayName: Check for required parameters
  - bash: |
      if [[ -z "$(system.pullRequest.sourceBranch)" ]]; then
        echo "##vso[task.setvariable variable=SOURCE_BRANCH;]$(build.sourceBranchName)"
      else
        echo "##vso[task.setvariable variable=SOURCE_BRANCH;]$(system.pullRequest.sourceBranch)"
      fi
    displayName: Set source branch
  - task: CacheBeta@0
    inputs:
      key: |
        yarn-packages-${{ parameters.version }}-$(SOURCE_BRANCH)
        $(build.sourcesDirectory)/yarn.lock
      path: ${{ parameters.path }}
    displayName: Cache Yarn packages
