parameters:
  branch: ''
  path: ''
  version: 'v1'
steps:
  - bash: |
      if [ -z "$PATH_PARAMETER" ]; then
        echo "##vso[task.logissue type=error;]Missing template parameter \"path\""
        echo "##vso[task.complete result=Failed;]"
      fi
    env:
      PATH_PARAMETER: ${{ parameters.path }}
    displayName: Check for required parameters
  - task: CacheBeta@0
    inputs:
      key: |
        yarn-packages-${{ parameters.version }}-${{ coalesce(parameters.branch, variables.build.sourceBranchName, 'master')  }}
        $(build.sourcesDirectory)/yarn.lock
      path: ${{ parameters.path }}
    displayName: Cache Yarn packages
