name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Setup Node
        uses: actions/setup-node@v1.1.1
        with:
          version: 10.16.0
      - name: Install Node dependencies
        run: yarn install --frozen-lockfile
